name: devsecops-project-v2

on:
  push:
    branches: 
    - develop
    - main

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Ecoho a string 
        run: echo "some text"






